""" This modules defines all choices used in the app """

SalutationOptions = [
    ('male', 'Herr'),
    ('female', 'Frau'),
    ('other', 'Diverse'),
]

FilesCoices = [
    ('Lebenslauf', 'Lebenslauf'),
    ('Zeugnisse', 'Zeugnisse'),
    ('Sonstiges', 'Sonstiges'),
]


TrainigChoices =[
    ('Ausbildung', 'Ausbildung'),
    ('keine', 'keine'),
]

CampusChoices = [
    ('Berlin', 'Berlin'),
    ('Düsseldorf', 'Düsseldorf'),
]

DegreeChoices = [
    ('Abitur', 'Abitur'),
    ('Fachabitur', 'Fachabitur'),
    ('Hauptschulabschluss', 'Hauptschulabschluss'),
    ('Realschulabschluss', 'Realschulabschluss'),
    ('kein Abschluss', 'kein Abschluss'),
    ('andere', 'andere'),
]
DiplomaChoices = [
    ('Abitur', 'Abitur'),
    ('Fachabitur', 'Fachabitur'),
    ('Hauptschulabschluss', 'Hauptschulabschluss'),
    ('Realschulabschluss', 'Realschulabschluss'),
    ('kein Abschluss', 'kein Abschluss'),
    ('andere', 'andere'),
]
StateChoices = [
    ('BW', 'Baden-Württemberg'),
    ('BY', 'Bayern'),
    ('BE', 'Berlin'),
    ('BB', 'Brandenburg'),
    ('HB', 'Bremen'),
    ('HH', 'Hamburg'),
    ('HE', 'Hessen'),
    ('MV', 'Mecklenburg-Vorpommern'),
    ('NI', 'Niedersachsen'),
    ('NW', 'Nordrhein-Westfalen'),
    ('RP', 'Rheinland-Pfalz'),
    ('SL', 'Saarland'),
    ('SN', 'Sachsen'),
    ('ST', 'Sachsen-Anhalt'),
    ('SH', 'Schleswig-Holstein'),
    ('TH', 'Thüringen'),
]

CountryChoices = [

    ('DE', 'Deutschland'),
    ('AT', 'Österreich'),
    ('CH', 'Schweiz'),
    ('TE', 'Test'),
]

MaritalStatusChoices = [
    ('ledig', 'Ledig'),
    ('verheiratet', 'Verheiratet'),
    ('geschieden', 'Geschieden'),
    ('verwitwet', 'Verwitwet'),
    ('partnerschaft', 'In einer Partnerschaft')
]

NationalityChoices = [
    ('AF', 'Afghanisch'),
    ('AL', 'Albanisch'),
    ('DZ', 'Algerisch'),
    ('AD', 'Andorranisch'),
    ('AO', 'Angolanisch'),
    ('AG', 'Antiguanisch'),
    ('AR', 'Argentinisch'),
    ('AM', 'Armenisch'),
    ('AU', 'Australisch'),
    ('AT', 'Österreichisch'),
    ('AZ', 'Aserbaidschanisch'),
    ('BS', 'Bahamesisch'),
    ('BH', 'Bahrainisch'),
    ('BD', 'Bangladeschisch'),
    ('BB', 'Barbadisch'),
    ('BY', 'Belarussisch'),
    ('BE', 'Belgisch'),
    ('BZ', 'Belizisch'),
    ('BJ', 'Beninisch'),
    ('BT', 'Bhutanisch'),
    ('BO', 'Bolivianisch'),
    ('BA', 'Bosnisch'),
    ('BW', 'Botswanisch'),
    ('BR', 'Brasilianisch'),
    ('BN', 'Bruneiisch'),
    ('BG', 'Bulgarisch'),
    ('BF', 'Burkinisch'),
    ('BI', 'Burundisch'),
    ('KH', 'Kambodschanisch'),
    ('CM', 'Kamerunisch'),
    ('CA', 'Kanadisch'),
    ('CV', 'Kapverdisch'),
    ('CF', 'Zentralafrikanisch'),
    ('TD', 'Tschadisch'),
    ('CL', 'Chilenisch'),
    ('CN', 'Chinesisch'),
    ('CO', 'Kolumbianisch'),
    ('KM', 'Komorisch'),
    ('CG', 'Kongolesisch (Brazzaville)'),
    ('CD', 'Kongolesisch (Kinshasa)'),
    ('CR', 'Costa-ricanisch'),
    ('HR', 'Kroatisch'),
    ('CU', 'Kubanisch'),
    ('CY', 'Zyprisch'),
    ('CZ', 'Tschechisch'),
    ('DK', 'Dänisch'),
    ('DJ', 'Dschibutisch'),
    ('DM', 'Dominicanisch'),
    ('DO', 'Dominikanisch (Republik)'),
    ('EC', 'Ecuadorianisch'),
    ('EG', 'Ägyptisch'),
    ('SV', 'Salvadorianisch'),
    ('GQ', 'Äquatorialguineisch'),
    ('ER', 'Eritreisch'),
    ('EE', 'Estnisch'),
    ('SZ', 'Eswatinisch'),
    ('ET', 'Äthiopisch'),
    ('FJ', 'Fidschianisch'),
    ('FI', 'Finnisch'),
    ('FR', 'Französisch'),
    ('GA', 'Gabunisch'),
    ('GM', 'Gambisch'),
    ('GE', 'Georgisch'),
    ('DE', 'Deutsch'),
    ('GH', 'Ghanaisch'),
    ('GR', 'Griechisch'),
    ('GD', 'Grenadisch'),
    ('GT', 'Guatemaltekisch'),
    ('GN', 'Guineisch'),
    ('GW', 'Guinea-bissauisch'),
    ('GY', 'Guyanisch'),
    ('HT', 'Haitianisch'),
    ('HN', 'Honduranisch'),
    ('HU', 'Ungarisch'),
    ('IS', 'Isländisch'),
    ('IN', 'Indisch'),
    ('ID', 'Indonesisch'),
    ('IR', 'Iranisch'),
    ('IQ', 'Irakisch'),
    ('IE', 'Irisch'),
    ('IL', 'Israelisch'),
    ('IT', 'Italienisch'),
    ('CI', 'Ivorisch'),
    ('JM', 'Jamaikanisch'),
    ('JP', 'Japanisch'),
    ('JO', 'Jordanisch'),
    ('KZ', 'Kasachisch'),
    ('KE', 'Kenyisch'),
    ('KI', 'Kiribatisch'),
    ('KP', 'Nordkoreanisch'),
    ('KR', 'Südkoreanisch'),
    ('KW', 'Kuwaitisch'),
    ('KG', 'Kirgisisch'),
    ('LA', 'Laotisch'),
    ('LV', 'Lettisch'),
    ('LB', 'Libanesisch'),
    ('LS', 'Lesothisch'),
    ('LR', 'Liberianisch'),
    ('LY', 'Libysch'),
    ('LI', 'Liechtensteinisch'),
    ('LT', 'Litauisch'),
    ('LU', 'Luxemburgisch'),
    ('MG', 'Madagassisch'),
    ('MW', 'Malawisch'),
    ('MY', 'Malaysisch'),
    ('MV', 'Maledivisch'),
    ('ML', 'Malisch'),
    ('MT', 'Maltesisch'),
    ('MH', 'Marshallisch'),
    ('MR', 'Mauretanisch'),
    ('MU', 'Mauritisch'),
    ('MX', 'Mexikanisch'),
    ('FM', 'Mikronesisch'),
    ('MD', 'Moldauisch'),
    ('MC', 'Monégassisch'),
    ('MN', 'Mongolisch'),
    ('ME', 'Montenegrinisch'),
    ('MA', 'Marokkanisch'),
    ('MZ', 'Mosambikanisch'),
    ('MM', 'Myanmaresisch'),
    ('NA', 'Namibisch'),
    ('NR', 'Nauruisch'),
    ('NP', 'Nepalesisch'),
    ('NL', 'Niederländisch'),
    ('NZ', 'Neuseeländisch'),
    ('NI', 'Nicaraguanisch'),
    ('NE', 'Nigrisch'),
    ('NG', 'Nigerianisch'),
    ('MK', 'Nordmazedonisch'),
    ('NO', 'Norwegisch'),
    ('OM', 'Omanisch'),
    ('PK', 'Pakistanisch'),
    ('PW', 'Palauisch'),
    ('PA', 'Panamaisch'),
    ('PG', 'Papua-neuguineisch'),
    ('PY', 'Paraguayisch'),
    ('PE', 'Peruanisch'),
    ('PH', 'Philippinisch'),
    ('PL', 'Polnisch'),
    ('PT', 'Portugiesisch'),
    ('QA', 'Katarisch'),
    ('RO', 'Rumänisch'),
    ('RU', 'Russisch'),
    ('RW', 'Ruandisch'),
    ('KN', 'St. Kitts und Nevis'),
    ('LC', 'St. Lucianisch'),
    ('VC', 'St. Vincent und die Grenadinen'),
    ('WS', 'Samoanisch'),
    ('SM', 'San-marinesisch'),
    ('ST', 'São-toméisch'),
    ('SA', 'Saudi-arabisch'),
    ('SN', 'Senegalesisch'),
    ('RS', 'Serbisch'),
    ('SC', 'Seychellisch'),
    ('SL', 'Sierra-leonisch'),
    ('SG', 'Singapurisch'),
    ('SK', 'Slowakisch'),
    ('SI', 'Slowenisch'),
    ('SB', 'Salomonen'),
    ('SO', 'Somalisch'),
    ('ZA', 'Südafrikanisch'),
    ('SS', 'Südsudanesisch'),
    ('ES', 'Spanisch'),
    ('LK', 'Sri-lankisch'),
    ('SD', 'Sudanesisch'),
    ('SR', 'Surinamisch'),
    ('SE', 'Schwedisch'),
    ('CH', 'Schweizerisch'),
    ('SY', 'Syrisch'),
    ('TW', 'Taiwanisch'),
    ('TJ', 'Tadschikisch'),
    ('TZ', 'Tansanisch'),
    ('TH', 'Thailändisch'),
    ('TL', 'Timoresisch'),
    ('TG', 'Togolesisch'),
    ('TO', 'Tongaisch'),
    ('TT', 'Trinidadisch'),
    ('TN', 'Tunesisch'),
    ('TR', 'Türkisch'),
    ('TM', 'Turkmenisch'),
    ('TV', 'Tuvaluisch'),
    ('UG', 'Ugandisch'),
    ('UA', 'Ukrainisch'),
    ('AE', 'Vereinigte Arabische Emirate'),
    ('GB', 'Britisch'),
    ('US', 'Amerikanisch'),
    ('UY', 'Uruguayisch'),
    ('UZ', 'Usbekisch'),
    ('VU', 'Vanuatuisch'),
    ('VA', 'Vatikanisch'),
    ('VE', 'Venezolanisch'),
    ('VN', 'Vietnamesisch'),
    ('YE', 'Jemenitisch'),
    ('ZM', 'Sambisch'),
    ('ZW', 'Simbabwisch')
]